config/routes.rb
Blog::Application.routes.draw do
  root 'posts#index'

  devise_for :users
  resources :posts, only: [:index, :show, :new, :create, :edit, :update] do
    resources :comments, only: [:create]
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post,
    inverse_of: :comments

  validates_presence_of :body
  validates_presence_of :post

  validates_email_format_of :email

end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments,
    inverse_of: :post,
    dependent: :destroy

  validates_presence_of :title
  validates_presence_of :content

  validate :john_approves_of_title

  def john_approves_of_title
    if title.present? && title.length < 4
      errors.add(:title, "is not approved by John")
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # /posts/:post_id/comments
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)

    # The line above does the same thing, but in one line :)
    # @comment = Comment.new(comment_params)
    # @comment.post = @post

    if @comment.save
      redirect_to post_path(@post), notice: "Cool story breux"
    else
      render template: "posts/show"
    end
  end

  protected 
  def comment_params
    params.require(:comment).permit(:email, :body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to '/posts', notice: "Post saved successfully."
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update_attributes(post_params)
      redirect_to '/posts', notice: "Post saved successfully."
    else
      render :edit
    end
  end

  protected 
  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Werewolf Mafia Blog" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <%= render 'shared/navbar' %>

  <body>
    <% flash.each do |name, msg| %>
      <div data-alert class="alert-box">
        <%= msg %>
        <a href="#" class="close">&times;</a></div>
    <% end %>

    <div class="row">
      <div class="small-12 columns">
        <%= yield %>
      </div>
    </div>

    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/posts/_form.html.erb
<% if post.errors.any? %>
  <ul>
    <% post.errors.full_messages.each do |error| %>
      <li><%= error %></li> 
    <% end %>
  </ul>
<% end %>

<%= form_for(post) do |f| %>
  <div>
    <%= f.label(:title) %>
    <%= f.text_field(:title) %>
  </div>

  <div>
    <%= f.label(:content) %>
    <%= f.text_area(:content) %>
  </div>

  <%= f.submit 'Save' %>
<% end %>

app/views/posts/_post.html.erb
<h3><%= link_to(post.title, post_path(post)) %></h3>
<p><%= post.content %></p>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render "posts/form", post: @post %>

app/views/posts/index.html.erb
<h1>Posts Index</h1>

<%= link_to 'Add a Post', new_post_path %>

<% @posts.each do |post| %>
  <%= render "posts/post", post: post  %>
<% end %>

app/views/posts/new.html.erb
<h1>Create a Post</h1>

<%= link_to 'Back to Posts', posts_path %>

<%= render "posts/form", post: @post %>

app/views/posts/show.html.erb
<%= link_to "Back to Posts", posts_path %>

<h1><%= @post.title %></h1>

<p><%= @post.content %></p>

<% if @post.comments.empty? %>
  <p>There aren't any comments yet.</p>
<% else %>
  <ul>
    <% @post.comments.each do |comment| %>
      <li>
        <%= comment.email %>
        <%= comment.body %>
      </li>
    <% end %>
  </ul>
<% end %>
<%= binding.pry %>
<h4>Add a Comment</h4>
<%= form_for([@post, @comment]) do |f| %>
  <% if @comment.errors.any? %>
    <ul>
      <% @comment.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  <% end %>

  <div>
    <%= f.label(:email) %>
    <%= f.text_field(:email) %>
  </div>

  <div>
    <%= f.label(:body) %>
    <%= f.text_area(:body) %>
  </div>

  <%= f.submit "Save comment", class: "button" %>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to 'W.M Blog', root_path %></h1>
    </li>
  </ul>

  <section class="top-bar-section">
    <ul class="right">
    <% if user_signed_in? %>
      <li class='label'>Signed in as <%= current_user.email %>. Not you?</li>
      <%= link_to 'Sign out', destroy_user_session_path %>
    <% else %>
        <li><%= link_to 'Sign up', new_user_registration_path %></li>
        <li class="active"><%= link_to 'Sign in', user_session_path %></li>
        </li>
      </ul>
    <% end %>
  </section>
</nav>